security:

    providers:
        our_db_provider:
            entity:
                class: App\Entity\Member
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            logout_on_user_change: true
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: home

    encoders:
        App\Entity\Member:
            algorithm: bcrypt
            cost: 13

    role_hierarchy:
        ROLE_ADMIN:   ROLE_USER

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }